import {
  Apple,
  Briefcase,
  Building2,
  Calculator,
  Compass,
  FileBadge,
  Flame,
  HandHelping,
  HardHat,
  HeartHandshake,
  IdCard,
  LandPlot,
  Landmark,
  LucideIcon,
  Megaphone,
  Monitor,
  Package,
  Palmtree,
  PieChart,
  Radio,
  Scale,
  Shield,
  ShieldAlert,
  Siren,
  Smile,
  Sprout,
  Stethoscope,
  Store,
  TreePine,
  User,
  UserCheck,
  Utensils,
  Wallet,
} from 'lucide-react';

// 1. Map the slugs to specific Lucide icons
export const officeIcons: Record<string, LucideIcon> = {
  // Municipal Departments
  'operation-center': Radio,
  'gender-and-development-office': HeartHandshake,
  'local-civil-registry-office': FileBadge,
  'municipal-planning-and-development-office': Compass,
  'municipal-engineering-office': HardHat,
  'municipal-assessors-office': LandPlot,
  'municipal-social-welfare-development-office': HandHelping,
  'municipal-environment-and-natural-resources-office': TreePine,
  'municipal-treasurers-office': Wallet,
  'public-information-office': Megaphone,
  'municipal-budget-office': PieChart,
  'municipal-accounting-office': Calculator,
  'municipal-human-resource-management-office': UserCheck,
  'municipal-tourism-office': Palmtree,
  'information-and-communication-systems-office': Monitor,
  'local-youth-and-development-office': Smile,
  'municipal-agriculture-office': Sprout,
  'municipal-mdrrmo-office': Siren,
  'municipal-police-station': ShieldAlert,
  'municipal-health-office': Stethoscope,
  'bureau-fire-protection': Flame,
  'business-permit-and-licensing-office': Briefcase,
  'municipal-general-services-office': Package,
  'persons-with-disability-affairs-office': User,
  'municipal-urban-development-and-housing-office': Building2,
  'office-senior-citizens-affairs': User,
  'municipal-nutrition-office': Apple,
  'public-employment-service-office': IdCard,
  'municipal-local-government-operations-office': Landmark,
  // Economic Enterprises
  market: Store,
  slaughterhouse: Utensils,
  // Public Safety
  'public-order-and-safety-office': Shield,
  // Committees
  'bids-and-awards-committee': Scale,
};
